### ISSUE TITLE
Is there a way to query parsec-service from parsec-tool regarding the current parameters in the config.toml

### ISSUE THREAD

**Issue by jainvikas8** [parallaxsecond/parsec-tool#122]
Depending on the platform, if we want to cross-verify the current configuration of the parsec-service, Is there a way to have a command option to **read** out the current config parameters set for the parsec-service?

If there are any passwords/pins in the config.toml, probably those can be encrypted as done by /dev/random?

**Comment by tgonzalezorlandoarm** [comment]
Neither the parsec-tool nor any parsec client should be able to query the configuration of the parsec-service. For this reason, we are closing this ticket.
For debugging purposes on the parsec-service side, you can directly check the written config.toml.
