### ISSUE TITLE
Add encrypt/decrypt support

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec-tool#27]
### Summary
Add commands in support of encryption and decryption of data with nominated keys.

### Details
Add `encrypt` and `decrypt` commands to the tool. Possible specifications below (subject to discussion).

Commands should accept a `--key-name` parameter to follow the convention of existing commands that deal with keys.

Commands should write cypher/plaintext to standard output by default, but should also accept an `--out-file` parameter allowing a file path to be specified instead.

Commands should read cypher/plaintext from standard input by default, but should also accept an `--in-file` parameter allowing a file path to be specified instead.

Commands should accept an optional `--base64` switch to indicate base64 processing of input/output. When specified, input should be base64-decoded prior to processing, and output should be base64-encoded after processing. By default, both input and output are raw binary.

Functionality can be limited to what the Parsec service supports (asymmetric encryption currently), but the CLI design should be such that it will support future use cases without breaking changes to scripts.

Data sizes can be limited (since Parsec does not yet support multi-part buffering). However, the CLI should be designed to scale to indefinitely-sized input/output in the future. The important thing is that we shouldn't make breaking changes when new functionality appears in the future.

**Comment by hug-dev** [comment]
I was first thinking that `encrypt`/`decrypt` should be prefixed with `asym` to make it clear that we are doing asymmetric encryption/decryption but actually, since all our Cipher/Asymmetric/AEAD share similar interface, we could just use `encrypt` and use the algorithm in the key policy to check what is the operation to do? For AEAD there would be more parameters (nonce and additional data) but those could be added as flag options?

**Comment by hug-dev** [comment]
For now, only `decrypt` will be implemented as it is the operation that needs the private part of the key stored in Parsec (and that only asymmetric encryption is supported at the moment). A new issue can be opened for `encrypt` later on if needed.
