### ISSUE TITLE
Add support for sign/verify

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-tool#31]
Once #27 is done, it should not be too hard to use similar features for signing/verifying.

Similarly commands `sign` and `verify` could be added. Currently as we only support the `SignHash`/`VerifyHash` commands we could just expect a hash or perform the hash in software in the tool.

We can use similar techniques as in #27 for the input/output file.

**Comment by ionut-arm** [comment]
The one thing this has different from encrypting is the length of the message - for encryption, the message *must* fit, whereas for signing we can hash the input if it doesn't have the correct length. So I propose the following: after the tool gathers the input data it checks the size. If the size exceeds the lengths of a digest, we hash it with the correct algorithm (in software) and send the result for signing. In the future, if there will be demand for it, we can add a `--hash` flag to always hash even if the length is the same as for a digest (and maybe a `--sign-message` to force the tool to call the `psa_sign_message` operation)

**Comment by hug-dev** [comment]
Similarly than for `encrypt`, let's focus on `sign` for now and add `verify` later if needed.
