### ISSUE TITLE
Add basic CLI tests on the CI

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-tool#42]
The CI should have Parsec running with the Mbed Crypto provider and test various commands with the `parsec-tool` to check that it works properly, that the commands stay stable and that the output is correct.

**Comment by ionut-arm** [comment]
Would be nice if we could do stuff like we do for the service and test the output of the CLI using, e.g., `openssl`

**Comment by hug-dev** [comment]
Yes that's a good idea! If we use compatible formats 😬
