### ISSUE TITLE
--provider option for list-opcodes is not consistent

### ISSUE THREAD

**Issue by ggardet** [parallaxsecond/parsec-tool#53]
`parsec-tool` help states that `--provider` option can be passed right after `parsec-tool` call, before subcommand. If omitted, the default provider is used.

But for `list-opcodes`, this does not work. `--provider` cannot be omitted and must be _after_  `list-opcodes` subcommand.

**Comment by hug-dev** [comment]
Hello 👋 
Thanks for the report.
Actually there are two `--provider` options for `list-opcodes`:
- the one common to all subcommands which is to target which provider will handle the operation. As `list-opcodes` is a core operation, it will always be targeted at the core provider anyway, so this `--provider` option is ignored. This option makes sense for crypto operations where it is defaulted to the default provider.
- the one specifically for the `list-opcodes` operation (the `provider_id` [parameter](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/list_opcodes.html#parameters)) to specify which provider this operation should ask

In that sense it is not a bug per se but it could definitely be an improvement for `list-opcodes` to use the default provider as parameter if not specified!
