### ISSUE TITLE
`ansi_term` is unmaintained

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-tool#87]
The `ansi_term` crate is now reported as unmaintained (see [here](https://rustsec.org/advisories/RUSTSEC-2021-0139)) - we need to migrate away from both `ansi_term` and `structopt` to address this. Apparently [clap v3 already offers some support for the migration](https://github.com/TeXitoi/structopt/issues/528#issuecomment-1221293811).

**Comment by paulhowardarm** [comment]
Do we need to tackle this as part of Sept release?

**Comment by ionut-arm** [comment]
I don't think it's critical, but it would be good to do it if we have the spare cycles! Same for both this and the service issues.

The crate covers functionality related to CLI features - I think we should be safe in both cases. For the service (for which I'm more worried), the CLI arguments are set/passed by the admin, so I'm not that worried.

**Comment by tgonzalezorlandoarm** [comment]
ansi_term was removed as part of https://github.com/parallaxsecond/parsec-tool/pull/107
